hf_model:
  name: cardiffnlp/twitter-roberta-base-sentiment-latest
  fine_tuned_name: Emanueleb/twitter-roberta-base-sentiment-latest-finetuned
  num_labels: 3
  label2id:
    negative: 0
    neutral: 1
    positive: 2

quality_thresholds:
  f1_min: 0.7
  accuracy_min: 0.7
