hf_model:
  name: cardiffnlp/twitter-roberta-base-sentiment-latest
  num_labels: 3
  label2id:
    negative: 0
    neutral: 1
    positive: 2

hf_hub_model_id: Emanueleb/twitter-roberta-base-sentiment-latest-finetuned

quality_thresholds:
  f1_min: 0.7
  accuracy_min: 0.7

kaggle_dataset:
  name: mdismielhossenabir/sentiment-analysis
  file_path: sentiment_analysis.csv