services:

  fastapi:
    build: 
      context: ..
      dockerfile: docker-env/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - HOST=0.0.0.0
    volumes:
      - models_data:/app/models
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=*
    command: >
      mlflow server
        --backend-store-uri sqlite:////mlflow/mlflow.db
        --host 0.0.0.0
        --allowed-hosts *
    volumes:
      - mlflow_data:/mlflow

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_storage:/var/lib/grafana
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - mlflow
      - prometheus

  airflow:
    build:
      context: ..
      dockerfile: docker-env/Dockerfile.airflow
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=sentiment-mlops-secret
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_OUTPUT_DIR=/opt/airflow/models
      - PYTHONPATH=/opt/airflow/src
    volumes:
      - ../dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - ../config.yaml:/opt/airflow/config.yaml
      - airflow_data:/opt/airflow
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com 2>/dev/null || true &&
        airflow scheduler & airflow webserver
      "
    depends_on:
      - mlflow

volumes:
  models_data:
  mlflow_data:
  grafana_storage:
  prometheus_data:
  airflow_data: